version: '3.5'

services:
  micro-urbanizations:
    image: gabrielmarin98/urbansys-micro-urbanizations-app:v0.1
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: npm start
  micro-users:
    image: gabrielmarin98/urbansys-micro-urbanizations-app:v0.1
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3001:3000
    command: npm start
   